# Generated by Django 2.2.3 on 2019-07-10 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DaysOff',
            new_name='Break',
        ),
    ]
